### ISSUE TITLE
Task 4 - class Time

### ISSUE THREAD

**Issue by Ruthietta** [Marimeiko/object-oriented-programming#46]
Spróbuj napisać klasę Time, która będzie odpowiadać za zarządzanie czasem w grze.

Klasa ta powinna informować inne klasy, takie jak Cargo, Ship, Store o upłynięciu każdego dnia.

Poczytaj czym jest wzorzec projektowy Observer.

**Comment by m-kop** [comment]
Task needs to be refactored to smart pointers
